# Generated by Django 4.0.5 on 2023-03-21 16:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_oil', models.FloatField(help_text='The amount of oil spilled (in gallons)')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sei', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDesc',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(help_text='The name of the project for which data collection is being done.', max_length=50)),
                ('location', models.CharField(help_text='The location where the data is mostly collected', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HuntingDisrupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_ResponseSlow_ReleaseHigh', models.FloatField(blank=True, default=0.728125, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('high_ResponseSlow_ReleaseLow', models.FloatField(blank=True, default=0.271875, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('high_ResponsePrompt_ReleaseHigh', models.FloatField(blank=True, default=0.4375, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('high_ResponsePrompt_ReleaseLow', models.FloatField(blank=True, default=0.4375, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('low_ResponseSlow_ReleaseHigh', models.FloatField(blank=True, default=0.728125, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('low_ResponseSlow_ReleaseLow', models.FloatField(blank=True, default=0.271875, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('low_ResponsePrompt_ReleaseHigh', models.FloatField(blank=True, default=0.4375, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('low_ResponsePrompt_ReleaseLow', models.FloatField(blank=True, default=0.4375, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('id_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theID.projectdesc')),
            ],
        ),
        migrations.CreateModel(
            name='CultureDisrupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highImpact_highRelease', models.FloatField(blank=True, default=0.728125, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('lowImpact_highRelease', models.FloatField(blank=True, default=0.271875, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('highImpact_lowRelease', models.FloatField(blank=True, default=0.4375, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('lowImpact_lowRelease', models.FloatField(blank=True, default=0.4375, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('id_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theID.projectdesc')),
            ],
        ),
    ]
