# Generated by Django 4.0.5 on 2023-04-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theID', '0003_rename_owner_projectdesc_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='user',
            new_name='user_id',
        ),
    ]
