# Generated by Django 4.0.5 on 2023-04-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theID', '0004_rename_user_scenario_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='user_id',
            new_name='user_id2',
        ),
    ]
