# Generated by Django 4.0.5 on 2023-04-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theID', '0005_rename_user_id_scenario_user_id2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='user_id2',
        ),
    ]
