# Generated by Django 4.0.5 on 2023-04-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theID', '0008_alter_scenario_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='id_f',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='theID.projectdesc'),
        ),
    ]
