# Generated by Django 4.0.5 on 2023-09-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theID', '0009_scenario_id_f'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersOfOSDSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.RemoveField(
            model_name='huntingdisrupmodel',
            name='id_f',
        ),
        migrations.RemoveField(
            model_name='huntingdisrupmodel',
            name='user',
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='id_f',
        ),
        migrations.DeleteModel(
            name='CultureDisrupModel',
        ),
        migrations.DeleteModel(
            name='HuntingDisrupModel',
        ),
    ]
