# Generated by Django 4.0.5 on 2023-09-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theID', '0010_usersofosdss_remove_huntingdisrupmodel_id_f_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='recovery_time',
            field=models.IntegerField(help_text='recovery time in years'),
        ),
    ]
