# Generated by Django 4.2.4 on 2023-09-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theID', '0011_alter_scenario_recovery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='recovery_time',
            field=models.IntegerField(help_text='projected number of years for impact calculation'),
        ),
    ]
