# Generated by Django 4.2.4 on 2023-09-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theID', '0012_alter_scenario_recovery_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='association_distrupt',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0),
        ),
        migrations.AddField(
            model_name='scenario',
            name='cult_distrupt',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0),
        ),
        migrations.AddField(
            model_name='scenario',
            name='hunt_distrupt',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0),
        ),
        migrations.AddField(
            model_name='scenario',
            name='psycholical_effect',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0),
        ),
        migrations.AddField(
            model_name='scenario',
            name='socio_distrupt',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0),
        ),
        migrations.AddField(
            model_name='scenario',
            name='trust',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0),
        ),
        migrations.AddField(
            model_name='scenario',
            name='water_effectOn',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0),
        ),
    ]
