# Generated by Django 4.0.5 on 2023-10-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theID', '0014_alter_scenario_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysSpentAtSea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='days_at_sea',
            field=models.IntegerField(choices=[(1, '5-10 days'), (2, '10-15 days'), (3, '15-20 days'), (4, '20-25 days')], default=1),
        ),
        migrations.AddField(
            model_name='scenario',
            name='flora_fauna_destruc',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0),
        ),
        migrations.AddField(
            model_name='scenario',
            name='oil_type',
            field=models.IntegerField(choices=[(0, 'Light'), (1, 'Medium'), (2, 'Heavy'), (3, 'Extra Heavy')], default=1),
        ),
        migrations.AddField(
            model_name='scenario',
            name='release',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0),
        ),
    ]
