# Generated by Django 4.2.4 on 2023-10-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theID', '0015_daysspentatsea_oiltype_scenario_days_at_sea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='rise_in_food_cost',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0),
        ),
        migrations.AddField(
            model_name='scenario',
            name='rise_in_health_expenses',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='compensation_amount',
            field=models.FloatField(verbose_name='An estimate of the compensation the government has announced'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='cult_distrupt',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0, verbose_name='How do you grade the impact of this spill on disruption of cultural activities, such as cultural events like certain practices of worship?'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='hunt_distrupt',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0, verbose_name='How do you grade the impact of this spill scenario on hunting activities, such as fishing?'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='population_size',
            field=models.IntegerField(verbose_name='Population size of the affected community'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='psycholical_effect',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0, verbose_name='How do you grade this impact as being the cause of psychological or mental disorders among community members such as depression?'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='quantity_of_oil',
            field=models.IntegerField(verbose_name='Quantity of oil spilled (in US gallons)'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='recovery_time',
            field=models.IntegerField(verbose_name='For how many years do you want to see the impact?'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='socio_distrupt',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0, verbose_name='How do you grade the impact of this spill on social harmony among the community members?'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='temperature',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Moderate'), (3, 'Low')], default=2, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='trust',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0, verbose_name='How do you grade a likely distrust between community and the federal government if the recovery is slow?'),
        ),
    ]
