# Generated by Django 5.0.6 on 2024-05-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theID', '0016_scenario_rise_in_food_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HYDROCARBTYPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MATERIAL_STRENGTH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VESSEL_SIZE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='hydrocarbonType',
            field=models.IntegerField(choices=[(1, 'Toxic'), (2, 'NonToxic')], default=1, verbose_name='The toxity of the hydrocarbon release, light oil is usually toxic?'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='material_strength',
            field=models.IntegerField(choices=[(1, 'Thin'), (2, 'Thick')], default=2, verbose_name='Was the material of manufacture of the vessel thin or thick?'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='response',
            field=models.IntegerField(choices=[(1, 'Slow'), (2, 'Prompt')], default=2, verbose_name='Was response fast or slow?'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='soil_damage',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0, verbose_name='The damage to soil in the seas'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='vessel_size',
            field=models.IntegerField(choices=[(1, 'Small'), (2, 'Big')], default=1, verbose_name='What was the size of the ship or vessel causing the spill?'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='days_at_sea',
            field=models.IntegerField(choices=[(1, '5-15 days'), (2, '15-25 days')], default=1),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='rise_in_food_cost',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0, verbose_name='How do you grade the rise in food cost by the impact of this spill?'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='rise_in_health_expenses',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0, verbose_name='How do you grade the rise in health expenses by the impact of this spill?'),
        ),
    ]
