# Generated by Django 5.0.6 on 2024-05-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theID', '0017_hydrocarbtype_material_strength_response_vessel_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SINGLEDOUBLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='hole_size',
            field=models.IntegerField(choices=[(1, 'Small'), (2, 'Big')], default=1),
        ),
        migrations.AddField(
            model_name='scenario',
            name='hull',
            field=models.IntegerField(choices=[(1, 'Single Hull'), (2, 'Double Hull')], default=1),
        ),
    ]
