# Generated by Django 5.0.6 on 2024-05-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theID', '0018_singledouble_scenario_hole_size_scenario_hull'),
    ]

    operations = [
        migrations.CreateModel(
            name='VOYAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='YESNO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='norgreg_zone',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
        ),
        migrations.AddField(
            model_name='scenario',
            name='voyage_geography',
            field=models.IntegerField(choices=[(1, 'Heavily iced'), (2, 'Medium iced'), (3, 'Low iced')], default=1),
        ),
    ]
