# Generated by Django 5.0.6 on 2024-05-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theID', '0020_scenario_crew_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='vessel_age',
            field=models.IntegerField(choices=[(1, '15 to 20 years old'), (2, '10 to 15 years old'), (3, '5 to 10 years old'), (4, '1 to 5 years old')], default=2),
        ),
    ]
